@startuml Manage Jobposition (DELETE)

header Sameple OnlineJobFair Sequence Diagram
footer Page %page% of %lastpage%
title "Manage Jobposition (DELETE)"

participant "Client" as client
participant "<<javaScript>>\n:server" as server
participant "<<router>>\njobposition:" as routerJobpositions
participant "<<middleware>>\n:auths" as auth
participant "<<controllers>>\n:jobpositions" as controllersJobpositions
participant "<<model>>\n:Jobposition" as modelJobposition
database "<<MongoDB>>\n:Jobposition" as JobpositionsDatabase

client->server ++:req.delete('/positions/:id')
server->routerJobpositions ++:app.use('/positions',jobposition)
routerJobpositions->auth ++:protect,authorize('admin')
routerJobpositions -> controllersJobpositions ++:deleteJobposition()
controllersJobpositions->modelJobposition ++:findById(req.params.id)
controllersJobpositions->modelJobposition :delte(req.body)
modelJobposition ->JobpositionsDatabase ++: JobpositionSchema
JobpositionsDatabase --> modelJobposition --: jobpositions
controllersJobpositions <-- modelJobposition --:jobpositions
controllersJobpositions->client --:response

@enduml