@startuml Manage Jobposition (PUT)

header Sameple OnlineJobFair Sequence Diagram
footer Page %page% of %lastpage%
title "Manage Jobposition (PUT)"

participant "Client" as client
participant "<<javaScript>>\n:server" as server
participant "<<router>>\njobposition:" as routerJobpositions
participant "<<middleware>>\n:auths" as auth
participant "<<controllers>>\n:jobpositions" as controllersJobpositions
participant "<<model>>\n:Jobposition" as modelJobposition
database "<<MongoDB>>\n:Jobposition" as JobpositionsDatabase

client->server ++:req.put('/positions/:id')
server->routerJobpositions ++:app.use('/positions',jobposition)
routerJobpositions-> auth ++:protect()
routerJobpositions -> controllersJobpositions ++:updateJobposition()
controllersJobpositions->modelJobposition ++:findByIdAndUpdate(req.params.id, req.body)
modelJobposition ->JobpositionsDatabase ++: JobpositionSchema
JobpositionsDatabase --> modelJobposition --: jobpositions
controllersJobpositions <-- modelJobposition --:jobpositions
controllersJobpositions->client --:response

@enduml